[ccds.ccd0]
cores = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

[ccds.ccd1]
cores = [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]

# usage:
# [process_bind]
# game1 = "ccd0"
# game2 = "ccd1"
# game3 = "ccd0"
[process_bind]
