name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore CPUAffinityManager.csproj
    
    - name: Build
      run: dotnet build CPUAffinityManager.csproj -c Release --no-restore
    
    - name: Publish
      run: dotnet publish CPUAffinityManager.csproj -c Release -r win-x64 --self-contained false /p:PublishSingleFile=true /p:PublishReadyToRun=true
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./bin/Release/net9.0-windows/win-x64/publish/CPUAffinityManager.exe
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 